name: ninjax
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jax
        python -m pip install jaxlib
        python -m pip install pytest
        python -m pip install dm-haiku
        python -m pip install flax
        python -m pip install optax
        python -m pip install cloudpickle
    # - name: Installation
    #   run: |
    #     python -m pip install -e .
    - name: Tests
      run: |
        python -m pytest tests
    - name: Examples
      run: |
        python -m examples.quickstart
        python -m examples.libraries
